import http from "k6/http";
import { check, sleep } from "k6";

const baseUrl = (__ENV.BASE_URL || "http://localhost:8080").replace(/\/$/, "");
const profile = __ENV.PROFILE || "smoke";

const profiles = {
  smoke: {
    executor: "shared-iterations",
    vus: 1,
    iterations: 3,
    maxDuration: "1m",
  },
  load: {
    executor: "constant-vus",
    vus: Number(__ENV.VUS || 10),
    duration: __ENV.DURATION || "2m",
  },
  stress: {
    executor: "ramping-vus",
    startVUs: 1,
    stages: [
      { duration: "30s", target: 10 },
      { duration: "1m", target: 25 },
      { duration: "30s", target: 50 },
      { duration: "30s", target: 0 },
    ],
    gracefulRampDown: "15s",
  },
};

if (!profiles[profile]) {
  throw new Error(`Unknown PROFILE '${profile}'. Use smoke, load, or stress.`);
}

export const options = {
  scenarios: { sprintforge_api: profiles[profile] },
  thresholds: {
    http_req_failed: ["rate<0.01"],
    http_req_duration: ["p(95)<1000", "p(99)<2000"],
    checks: ["rate>0.99"],
  },
  summaryTrendStats: ["min", "med", "avg", "p(90)", "p(95)", "p(99)", "max"],
};

export function setup() {
  const health = http.get(`${baseUrl}/actuator/health`, {
    tags: { name: "health-check" },
  });
  if (!check(health, { "service is ready": (response) => response.status === 200 })) {
    throw new Error(`Service is not ready: HTTP ${health.status}`);
  }

  const suffix = `${Date.now()}-${Math.floor(Math.random() * 100000)}`;
  const email = `k6-${suffix}@example.org`;
  const password = "LoadTest123!";
  const registration = http.post(
    `${baseUrl}/api/v1/auth/register`,
    JSON.stringify({ email, password, displayName: "k6 Load Tester" }),
    jsonParams("register"),
  );
  if (!check(registration, { "registration succeeds": (response) => response.status === 201 })) {
    throw new Error(`Registration failed: HTTP ${registration.status} ${registration.body}`);
  }

  const auth = registration.json();
  const projectKey = `K${String(Date.now()).slice(-10)}`;
  const project = http.post(
    `${baseUrl}/api/v1/projects`,
    JSON.stringify({
      name: `k6 performance run ${suffix}`,
      key: projectKey,
      description: `Generated by the ${profile} performance profile`,
    }),
    authParams(auth.token, "create-project"),
  );
  if (!check(project, { "project creation succeeds": (response) => response.status === 201 })) {
    throw new Error(`Project creation failed: HTTP ${project.status} ${project.body}`);
  }

  return {
    token: auth.token,
    userId: auth.user.id,
    projectId: project.json().id,
    runId: suffix,
  };
}

export default function (data) {
  const iteration = `${data.runId}-${__VU}-${__ITER}`;
  const created = http.post(
    `${baseUrl}/api/v1/projects/${data.projectId}/work-items`,
    JSON.stringify({
      title: `Load-tested work item ${iteration}`,
      description: "Created by the reproducible k6 workload",
      status: "TODO",
      priority: "MEDIUM",
      assigneeId: data.userId,
    }),
    authParams(data.token, "create-work-item"),
  );
  const createdOk = check(created, {
    "work item creation succeeds": (response) => response.status === 201,
  });
  if (!createdOk) {
    return;
  }

  const workItemId = created.json().id;
  const list = http.get(
    `${baseUrl}/api/v1/projects/${data.projectId}/work-items?status=TODO&page=0&size=20`,
    authParams(data.token, "list-work-items"),
  );
  check(list, {
    "work item list succeeds": (response) => response.status === 200,
  });

  const comment = http.post(
    `${baseUrl}/api/v1/projects/${data.projectId}/work-items/${workItemId}/comments`,
    JSON.stringify({ body: `Performance test comment ${iteration}` }),
    authParams(data.token, "create-comment"),
  );
  check(comment, {
    "comment creation succeeds": (response) => response.status === 201,
  });

  const summary = http.get(
    `${baseUrl}/api/v1/projects/${data.projectId}/work-items/summary`,
    authParams(data.token, "board-summary"),
  );
  check(summary, {
    "board summary succeeds": (response) => response.status === 200,
  });
  sleep(0.2);
}

function jsonParams(name) {
  return {
    headers: { "Content-Type": "application/json" },
    tags: { name },
  };
}

function authParams(token, name) {
  return {
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    tags: { name },
  };
}
